### PR TITLE
Added option to avoid animation on render

### PR DESCRIPTION
**Pull request by bitomule**
I've added data-animate-on-render option to disable animation on render. It could be useful inside #each loops where you don't want to animate the render, just when a new element is inserted or removed.

### CODE REVIEW

**Comment by frozeman** [comment]
Thanks, could you please also update the read me, so people will know about this addition?

**Comment by bitomule** [comment]
sure!

**Comment by bitomule** [comment]
added to readme. Is that enough?

**Comment by bitomule** [comment]
I think this brings a new problem. If animation after status is expected (opacity should be 1 for example) and I use the ignore render option then item is displayed with the wrong css (opacity 0 for example).

I think the best way to fix this is always run animation but with 0 time if no animation on rendered is true.

What do you think?

**Comment by bitomule** [comment]
sorry, my bad, that's the behavior before my change ;)

**Comment by bitomule** [comment]
Now it's back with all your code, just added the option to avoid animation on render and readme.

**Pull request merged**
